### ISSUE TITLE
Problem with Run

### ISSUE THREAD

**Issue by MariaRsA** [Rolfff/Visametric-Termin-Bot#2]
I tried to run the Bot but i recieve this Error -> UnboundLocalError: cannot access local variable 'GECKOPATH' where it is not associated with a value. Could you please help me?

**Comment by Rolfff** [comment]
Thank you for your request! Yes, i have forgotten to describe this point. Sorry. 
I will test it this evening.

**Comment by MariaRsA** [comment]
Thank you so much :)

**Comment by Rolfff** [comment]
Please reopen the problem if it still exists.
They have changed the CAPTCHA. Therefore I have to work further on the script.

**Comment by MariaRsA** [comment]
Thank you i will try it and let you know.
